baseURL = "maugomes.netlify.app"
languageCode = "en"
defaultContentLanguage = "en"
title = "Mauricio's Log Book"                         # site title  # 网站标题
theme = "zozo"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 50
paginate = 4                           # shows the number of articles  # 首页显示文章数量
enableEmoji = true
googleAnalytics = ""                   # your google analytics id
disqusShortname = "mmaugomes"                   # your discuss shortname

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]                               # essential                     # 必需
  name = "Maurício"

[blackfriday]
  smartypants = false

[[menu.main]]                          # config your menu  # 配置菜单
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archive"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "Chinese Study Notes 中文学习"
  weight = 20
  identifier = "chinese"
  url = "/chinese/"
[[menu.main]]
  name = "Reading List"
  weight = 25
  identifier = "readinglist"
  url = "/readinglist/"  
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = 40
  identifier = "about"
  url = "/about/"

[params]
  subTitle = ""                                       # site's subTitle  # 网站二级标题
  subsubtitle = "Hey there! This is my log book and portfolio, here I'll document some projects and articles. I'll also write on what I'm passionate about and what I study. Feel free to look around!"
  footerSlogan = ""                                   # site's footer slogan  # 网站页脚标语
  keywords = ["Hugo","theme","zozo"]                                  # site's keywords  # 网站关键字
  description = "logbook and portfolio"                        # site's description  # 网站描述
  enableMathJax = true                                                 # enable mathjax  # 是否使用mathjax（数学公式）
  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要
  mainSections = ["posts","post"]
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

# Your socail's url
[social]
  github = "https://github.com/maugomesqueiroz"


 # twitter = " "
 # facebook = " "
 # weibo = " "
 # instagram = " "

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
